# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backups_enable', models.BooleanField(default=True, verbose_name='backups enable')),
                ('last_run_backup', models.DateTimeField(blank=True, null=True, verbose_name='last run backup')),
                ('result', models.NullBooleanField(verbose_name='result of last backup')),
                ('run_time', models.DateTimeField(blank=True, null=True, verbose_name='every day time for run')),
                ('media_directories', models.TextField(default=b'[]', verbose_name='directories')),
            ],
            options={
                'verbose_name': 'Backup data',
                'verbose_name_plural': 'Backup data',
            },
        ),
        migrations.CreateModel(
            name='PerfCpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='\u0434\u0430\u0442\u0430')),
                ('value', models.FloatField(verbose_name='\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ('time',),
                'verbose_name': 'Perfomance cpu',
                'verbose_name_plural': 'Perfomance cpu',
            },
        ),
        migrations.CreateModel(
            name='PerfData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_last_time_5m', models.DateTimeField(blank=True, null=True, verbose_name='last run 5m')),
                ('run_last_time_10m', models.DateTimeField(blank=True, null=True, verbose_name='last run 10m')),
                ('run_last_time_30m', models.DateTimeField(blank=True, null=True, verbose_name='last run 30m')),
                ('run_last_time_1h', models.DateTimeField(blank=True, null=True, verbose_name='last run 1h')),
            ],
            options={
                'verbose_name': 'Perfomance data',
                'verbose_name_plural': 'Perfomance data',
            },
        ),
        migrations.CreateModel(
            name='PerfDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date')),
                ('total', models.BigIntegerField(verbose_name='total')),
                ('used', models.BigIntegerField(verbose_name='used')),
                ('free', models.BigIntegerField(verbose_name='free')),
                ('percent', models.IntegerField(verbose_name='percent')),
            ],
            options={
                'ordering': ('time',),
                'verbose_name': 'Perfomance disk',
                'verbose_name_plural': 'Perfomance disk',
            },
        ),
        migrations.CreateModel(
            name='PerfMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date')),
                ('total', models.BigIntegerField(verbose_name='total')),
                ('available', models.BigIntegerField(verbose_name='available')),
                ('percent', models.IntegerField(verbose_name='percent')),
                ('used', models.BigIntegerField(verbose_name='used')),
                ('free', models.BigIntegerField(verbose_name='free')),
                ('active', models.BigIntegerField(verbose_name='active')),
                ('inactive', models.BigIntegerField(verbose_name='inactive')),
                ('swap_total', models.BigIntegerField(verbose_name='swap total')),
                ('swap_used', models.BigIntegerField(verbose_name='swap used')),
                ('swap_free', models.BigIntegerField(verbose_name='swap free')),
                ('swap_percent', models.IntegerField(verbose_name='swap percent')),
            ],
            options={
                'ordering': ('time',),
                'verbose_name': 'Perfomance memory',
                'verbose_name_plural': 'Perfomance memory',
            },
        ),
        migrations.CreateModel(
            name='PerfNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date')),
                ('bytes_sent', models.BigIntegerField(verbose_name='bytes sent')),
                ('bytes_recv', models.BigIntegerField(verbose_name='bytes recv')),
                ('packets_sent', models.BigIntegerField(verbose_name='packets sent')),
                ('packets_recv', models.IntegerField(verbose_name='packets recv')),
                ('errin', models.BigIntegerField(verbose_name='errin')),
                ('errout', models.BigIntegerField(verbose_name='errout')),
                ('dropin', models.BigIntegerField(verbose_name='dropin')),
                ('dropout', models.BigIntegerField(verbose_name='dropout')),
            ],
            options={
                'ordering': ('time',),
                'verbose_name': 'Perfomance network',
                'verbose_name_plural': 'Perfomance network',
            },
        ),
        migrations.CreateModel(
            name='PerfProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date')),
                ('processes', models.TextField()),
            ],
            options={
                'ordering': ('time',),
                'verbose_name': 'Perfomance processes',
                'verbose_name_plural': 'Perfomance processes',
            },
        ),
        migrations.CreateModel(
            name='PerfSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date')),
                ('users', models.TextField()),
            ],
            options={
                'ordering': ('time',),
                'verbose_name': 'Perfomance system',
                'verbose_name_plural': 'Perfomance system',
            },
        ),
        migrations.CreateModel(
            name='SecurityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_last_login_attempt_incorrect', models.DateTimeField(blank=True, null=True, verbose_name='run last login attempt incorrect')),
                ('run_last_login_attempt_correct', models.DateTimeField(blank=True, null=True, verbose_name='run last login attempt correct')),
            ],
            options={
                'verbose_name': 'Security data',
                'verbose_name_plural': 'Security data',
            },
        ),
        migrations.CreateModel(
            name='SecurityLoginAttemptCorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True, verbose_name='date')),
                ('value', models.TextField(null=True, verbose_name='value')),
            ],
            options={
                'ordering': ('time',),
                'verbose_name': 'Security login attempt correct',
                'verbose_name_plural': 'Security login attempt correct',
            },
        ),
        migrations.CreateModel(
            name='SecurityLoginAttemptIncorrect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True, verbose_name='date')),
                ('value', models.TextField(null=True, verbose_name='value')),
            ],
            options={
                'ordering': ('time',),
                'verbose_name': 'Security login attempt incorrect',
                'verbose_name_plural': 'Security login attempt incorrect',
            },
        ),
    ]
