# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangodashpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securitydata',
            old_name='run_last_login_attemp_correct',
            new_name='run_last_login_attempt_correct',
        ),
        migrations.RenameField(
            model_name='securitydata',
            old_name='run_last_login_attemp_incorrect',
            new_name='run_last_login_attempt_incorrect',
        ),
    ]
