# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodashpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlLogStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='date')),
                ('value', models.TextField(verbose_name='value')),
            ],
            options={
                'ordering': ('time',),
                'verbose_name': 'Url requests statistics',
                'verbose_name_plural': 'Url requests statistics',
            },
        ),
    ]
