# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodashpanel', '0002_urllogstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllogstat',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='urllogstat',
            name='value',
            field=models.TextField(null=True, verbose_name='value'),
        ),
    ]
