# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodashpanel', '0002_auto_20170427_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backups_enable', models.BooleanField(default=True, verbose_name='backups enable')),
            ],
            options={
                'verbose_name': 'Settings data',
                'verbose_name_plural': 'Settings data',
            },
        ),
    ]
