# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodashpanel', '0004_auto_20170428_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupdata',
            options={'verbose_name': 'Backup data', 'verbose_name_plural': 'Backup data'},
        ),
        migrations.AddField(
            model_name='backupdata',
            name='media_directories',
            field=models.TextField(default=b'[]', verbose_name='directories'),
        ),
        migrations.AddField(
            model_name='backupdata',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='result of last backup'),
        ),
        migrations.AddField(
            model_name='backupdata',
            name='run_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last run backup'),
        ),
    ]
