# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodashpanel', '0005_auto_20170428_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupdata',
            name='run_time',
            field=models.TimeField(blank=True, null=True, verbose_name='run backup'),
        ),
    ]
